Fix popover and breadcrumb menu
Voog/design-longyearbyen pull request #187
Opened 2022-02-11 12:54 UTC by PeeterPaal

Closes #186

2022-02-14 13:46 UTC, pxska approved these changes
One comment, otherwise good!

2022-02-14 13:46 UTC, pxska commented on components/menu-breadcrumbs-sd.tpl
> +    <li class="selected menu-item {% if forloop.last %}current{% endif %}">
Here the `selected` class does provide a `font-weight` value, but it is the same as the `body` element's value. We can remove this.

2022-02-17 07:32 UTC, tanelj requested changes
Nice and works but one there is on issue with links:

* [ ] Links in product description area are not styled (browser default)

In product description:
<img width="442" alt="Screenshot 2022-02-17 at 09 31 27" src="https://user-images.githubusercontent.com/378755/154426908-123d2f8e-a733-4765-a676-5a04dfbe41cb.png">
In text area:
<img width="155" alt="Screenshot 2022-02-17 at 09 31 45" src="https://user-images.githubusercontent.com/378755/154426942-281b078d-cba5-4ed9-8333-a24043399de2.png">

2022-02-17 08:35 UTC, tanelj approved these changes

2022-02-17 13:53 UTC, pxska approved these changes

2022-02-17 13:55 UTC, merged