Improve auto-rendered product pages
Voog/design-longyearbyen pull request #189
Opened 2022-03-03 09:22 UTC by PeeterPaal

Closes #188

2022-03-09 14:51 UTC, tanelj requested changes
Nice but one minor issue.

2022-03-09 14:51 UTC, tanelj commented on components/template-head.tpl
>  {% comment %}{% stylesheet_link "main.css" %}{% endcomment %}
Should be:
```suggestion
<link href="{{ stylesheets_path }}/main.css?v={{ template_settings.version }}" media="screen" rel="stylesheet" type="text/css"/>
```

2022-03-09 15:18 UTC, tanelj approved these changes
Nice!

2022-03-10 10:07 UTC, pxska approved these changes
Looks good!

2022-03-10 11:14 UTC, merged